### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by jhoogeboom** [ryanss/podcastd#1]
does it need to be run from the src directory? if not I get this error:
```bash
Error: invalid argument
panic: open templates/home.html: no such file or directory

goroutine 1 [running]:
html/template.Must(0x0, 0x5a74658, 0xc8200136b0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/html/template/template.go:330 +0x4b
main.init()
	/Users/jorishoogeboom/.go/src/github.com/ryanss/podcastd/controllers.go:15 +0x1fe

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
```
if so, there is still an argument, what arguments are expected?
```bash
jjhb:podcastd jorishoogeboom$ podcastd
Error: invalid argument
```

btw I'm new to go, so excuse stupid mistakes.

**Comment by ryanss** [comment]
It does not need to be run from the source directory but file `config.json` and directory `templates` must be present in the same directory as the `podcastd` executable.
